apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  annotations:
    github.com/project-slug: dsilveira485/test-backstage
spec:
  type: other
  lifecycle: unknown
  owner: dsilveira485
